#!/bin/bash
py_bin="/Library/Developer/CommandLineTools/Library/Frameworks/Python3.framework/Versions/3.9/bin/python3"

if [ -x "$py_bin" ]; then
    version=$("$py_bin" --version 2>&1 | awk '{print $2}')
    echo "<result>$version</result>"
else
    echo "<result>Not Found</result>"
fi
